import { StyleSheet } from "react-native";
import colors from "../colors/colors";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.background,
  },
  label: {
    fontSize: 16,
    fontWeight: "bold",
    color: colors.secondary,
    marginTop: 10,
  },
  cardContainer: {
    backgroundColor: "#fff",
    padding: 16,
    borderRadius: 12,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    marginBottom: 20,
  },
  cardTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: colors.secondary,
    marginBottom: 12,
    textAlign: "center",
  },
  detailRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 10,
  },
  detailLabel: {
    marginLeft: 8,
    fontSize: 16,
    fontWeight: "bold",
    color: colors.secondary,
  },
  detailText: {
    fontSize: 16,
    marginTop: 4,
    marginBottom: 8,
    color: colors.primary,
    marginLeft: 28,
  },
  username: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 10,
    color: colors.dark,
    marginBottom: 10,
  },
  error: {
    backgroundColor: colors.error,
    justifyContent: "center",
    color: colors.dark,
    width: "100%",
    height: "auto",
  },
  navBar: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    backgroundColor: colors.lightBlue,
    color: colors.notification,
    width: "100%",
    height: "8%",
    padding: 10,
    marginBottom: 10,
  },
  disabledButton: {
    backgroundColor: colors.grayDark,
  },
  containerIndex: {
    flex: 1,
    color: colors.notification,
  },
  containerShowProfessores: {
    flex: 1,
    backgroundColor: colors.surface,
    marginBottom: 10,
    borderRadius: 5,
    padding: 10,
    borderWidth: 1,
    borderColor: colors.grayDark,
    marginLeft: 10,
    marginRight: 10,
    display: "flex",
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  containerDiretor: {
    color: colors.notification,
    marginTop: 10,
    marginBottom: "50%",
  },
  containerProfile: {
    flex: 1,
    color: colors.surface,
    marginTop: "50%",
  },
  text: {
    fontSize: 10,
    color: colors.textPrimary,
    marginBottom: 20,
    marginLeft: 10,
  },
  button: {
    backgroundColor: colors.primary,
    padding: 10,
    borderRadius: 5,
    marginLeft: 10,
    marginRight: 10,
  },
  textButton: {
    display: "flex",
    flexDirection: "row",
    padding: 10,
    borderRadius: 5,
    marginLeft: 10,
    marginRight: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  link: {
    color: colors.dark,
    textDecorationLine: "underline",
    marginTop: 10,
    marginLeft: 10,
    cursor: "pointer",
  },
  back: {
    backgroundColor: colors.primary,
    padding: 10,
    borderRadius: 5,
    width: 40,
    marginLeft: 10,
    marginVertical: 10,
  },
  textInput: {
    backgroundColor: colors.surface,
    borderColor: colors.error,
    borderRadius: 5,
    padding: 10,
    marginLeft: 10,
    marginRight: 10,
    marginBottom: 10,
    fontSize: 20,
  },
  background: {
    flex: 1,
    resizeMode: "cover",
    opacity: 2.8,
  },
});
export default styles;
